package Main.tools;

import java.awt.Image;

import Flash.Images.FImage;

import com.lss.flasher.Graphics.Sprite;
import com.lss.flasher.Graphics.SpriteSheet;

public class Textures {

	public static SpriteSheet tiles = new SpriteSheet("/textures/Sheets/tiles.png", 512);
	public static SpriteSheet house1 = new SpriteSheet("/textures/Sheets/house.png", 512);
	public static SpriteSheet newTiles = new SpriteSheet("/textures/Sheets/newTiles.png", 256, 16704);

	
	/*
	 * Generated by
	 */
	public static Sprite grass = new Sprite(32, 0, 0, newTiles);
	public static Sprite dirt = new Sprite(32, 1, 0, newTiles);
	public static Sprite redDirt = new Sprite(32, 2, 0, newTiles);
	public static Sprite sand = new Sprite(32, 3, 0, newTiles);
	public static Sprite cobble = new Sprite(32, 4, 0, newTiles);
	public static Sprite tiledFloor = new Sprite(32, 5, 0, newTiles);
	public static Sprite tilePath = new Sprite(32, 6, 0, newTiles);
	public static Sprite darkTilePath = new Sprite(32, 7, 0, newTiles);

	/*
	 * Market tent
	 */
	public static Sprite tent0 = new Sprite(32, 3, 240, newTiles);
	public static Sprite tent1 = new Sprite(32, 4, 240, newTiles);
	public static Sprite tent2 = new Sprite(32, 5, 240, newTiles);
	public static Sprite tent3 = new Sprite(32, 6, 240, newTiles);
	public static Sprite tent4 = new Sprite(32, 7, 240, newTiles);
	public static Sprite tent5 = new Sprite(32, 3, 241, newTiles);
	public static Sprite tent6 = new Sprite(32, 4, 241, newTiles);
	public static Sprite tent7 = new Sprite(32, 5, 241, newTiles);
	public static Sprite tent8 = new Sprite(32, 6, 241, newTiles);
	public static Sprite tent9 = new Sprite(32, 7, 241, newTiles);
	public static Sprite tent10 = new Sprite(32, 3, 242, newTiles);
	public static Sprite tent11 = new Sprite(32, 4, 242, newTiles);
	public static Sprite tent12 = new Sprite(32, 5, 242, newTiles);
	public static Sprite tent13 = new Sprite(32, 6, 242, newTiles);
	public static Sprite tent14 = new Sprite(32, 7, 242, newTiles);
	public static Sprite tent15 = new Sprite(32, 3, 243, newTiles);
	public static Sprite tent16 = new Sprite(32, 4, 243, newTiles);
	public static Sprite tent17 = new Sprite(32, 5, 243, newTiles);
	public static Sprite tent18 = new Sprite(32, 6, 243, newTiles);
	public static Sprite tent19 = new Sprite(32, 7, 243, newTiles);
	public static Sprite tent20 = new Sprite(32, 3, 244, newTiles);
	public static Sprite tent21 = new Sprite(32, 4, 244, newTiles);
	public static Sprite tent22 = new Sprite(32, 5, 244, newTiles);
	public static Sprite tent23 = new Sprite(32, 6, 244, newTiles);
	public static Sprite tent24 = new Sprite(32, 7, 244, newTiles);

	
	
	//House tiles
	public static Sprite stoneHouseUL = new Sprite(64, 0, 0, house1);
	public static Sprite stoneHouseUR = new Sprite(64, 2, 0, house1);
	public static Sprite stoneHouseDL = new Sprite(64, 0, 2, house1);
	public static Sprite stoneHouseDR = new Sprite(64, 2, 2, house1);
	public static Sprite stoneHouseUW = new Sprite(64, 1, 0, house1);
	public static Sprite stoneHouseDW = new Sprite(64, 1, 2, house1);
	public static Sprite stoneHouseLW = new Sprite(64, 0, 1, house1);
	public static Sprite stoneHouseRW = new Sprite(64, 2, 1, house1);

	public static Sprite door1 = new Sprite(64, 1, 3, house1);

	
	//Ground Tiles
//	public static Sprite grass = new Sprite(64, 0, 0, tiles);
//	public static Sprite sand = new Sprite(64, 1, 0, tiles);
	public static Sprite wood1 = new Sprite(64, 1, 1, tiles);

	//Liquids
	public static Sprite water = new Sprite(64, 0, 1, tiles);
	public static Sprite water1 = new Sprite(64, 0, 2, tiles);
	
	public static Sprite lava = new Sprite(64, 2, 0, tiles);
	public static Sprite lava1 = new Sprite(64, 2, 1, tiles);
	
	
	//Particles
	public static Image fireParticle = FImage.loadImage("/textures/Particles/fireParticle.png");
}
